In [1]:
import numpy as np
import pandas as pd
import matplotlib

In [11]:
# 이것은 오래걸리므로 한번만 실행할것 그래서 셀
data = np.genfromtxt("ratings.dat",delimiter="::",dtype=np.int64, encoding="utf-8",autostrip=True)

(1000209, 4)

In [14]:
# 예시데이터의 구조
# user::movie::rating::timestamp
data[:5]
data[:,2].mean()

np.float64(3.581564453029317)

In [18]:
user_ids = np.unique(data[:,0])
user_ids.shape

(6040,)

In [19]:
mean_values = []
for user_id in user_ids:
    # data 중 userid 가 같은 행에 대해 모든 열을 가져옴
    data_for_user = data[data[:,0]==user_id,:]
    # 그 모든 행의 2(rating)에 대해 평균값 구함
    value = data_for_user[:,2].mean()
    # 이 임의의 한 유저의 rating 평균을 저장
    mean_values.append(value)

[np.float64(4.188679245283019), np.float64(3.7131782945736433), np.float64(3.9019607843137254), np.float64(4.190476190476191), np.float64(3.1464646464646466)]


In [21]:
mean_array = np.array(mean_values,dtype=np.float32)
print(mean_array[:5])
print(mean_array.shape)

[4.188679  3.7131784 3.9019608 4.1904764 3.1464646]
(6040,)


In [22]:
np.savetxt("result.csv",mean_array,delimiter=",",fmt="%.2f")

In [46]:
# 기본 실습 1
sq_three_np_array = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
# sq_three_np_array[0]
# sq_three_np_array[:,1]
sq_three_np_array[1:,1:]

array([[5, 6],
       [8, 9]])

In [34]:
# 기본 실습 2
first_nparray = np.array([1,2,3])
second_nparray = np.array([4,5,6])
# first_nparray+second_nparray
# first_nparray-second_nparray
# first_nparray*second_nparray
# first_nparray/second_nparray

array([0.25, 0.4 , 0.5 ])

In [36]:
# 기본 실습 3
list_data = [10, 20, 30, 40, 50]
nparray_data = np.array(list_data)
type(nparray_data)

numpy.ndarray

In [40]:
# userId,movieId,rating
mini_data = np.genfromtxt("mini_ratings.csv",delimiter=",",dtype=np.float32, encoding="utf-8",autostrip=True)
print(mini_data[:5])

[[ 3.   6.   3.7]
 [ 5.  10.   3.1]
 [ 3.   2.   2.7]
 [ 1.   9.   1.7]
 [ 3.   8.   2.4]]


In [41]:
mini_data[:,2].mean()

np.float32(3.0750003)

In [48]:
mean_of_rating_array = []
unique_user_id = np.unique(mini_data[:,0])
for user_id in unique_user_id:
    rating_of_a_user = mini_data[mini_data[:,0]==user_id,2]
    mean_of_rating_array.append(rating_of_a_user.mean())
np.savetxt("mini_ratings_users_rating_mean.csv",mean_of_rating_array,delimiter=",",fmt="%.2f")

In [53]:
user_ids = np.array(mini_data[:,0])
ratings_only = np.array(mini_data[:,2])
unique_user_id = np.unique(mini_data[:,0])
mini_rating_users_rating_avg = {
    # user_ids == user 은 True, False 를 반환하는게 아니라 user_ids 길이와 같은 nparray를 반환
    # 그 리스트는 True,False 로 채워져 있음
    # 그러니 ratings_only 에서 True인 순서의 ratings_only 만 남긴 nparray 가 되는 것
    # 즉 이 방법을 쓰려면 user_ids 와 ratings_only 가 같은 data에서 나올 필요가 있고 정렬이 변경되지 않아야 함
    user: np.mean(ratings_only[user_ids == user]) for user in unique_user_id
}
df = pd.DataFrame(list(mini_rating_users_rating_avg.items()), columns=["UserID", "AverageRating"])
df.to_csv("user_avg_ratings.csv", index=False)