In [2]:
import numpy as np
import pandas as pd
import matplotlib

In [2]:
# numpy
# 벡터 및 행렬 연산에 특화
# array 단위로 데이터 관리
# numpy array는 정적 메모리 할당
# 텐서플로우에 효과적 사용
# import -> np.array(list) 로 python list형식을 numpy array형식으로 형변환
python_list = [1,2,3,4,5,6]
numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5 6]


In [3]:
# numpy array 내장함수 .mean() 평균값
numpy_array.mean()

np.float64(3.5)

In [4]:
# np.array(list).reshape(행,열)
numpy_array2 = np.array(python_list).reshape(2,3)
print(numpy_array2)

[[1 2 3]
 [4 5 6]]


In [5]:
# np.ones() parameter 로 인자, [행,열], 물론 위에서 처럼 1차원으로만들고 reshape 가능
y1=np.ones(10) #1차원 배열에 1채우기
y2=np.ones([3,4]) #2차원 배열에 1채우기
y3=np.ones(12).reshape(3,4) # y2와 동일
print('y1')
print(y1)
print('y2')
print(y2)
print('y3')
print(y3)

y1
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
y2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
y3
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# np.zeros() ones()와 같음
y4=np.zeros(10) #1차원 배열에 1채우기
y5=np.zeros((3,4)) #2차원 배열에 1채우기
y6=np.zeros(12).reshape(3,4) # y5와 동일
print('y4')
print(y4)
print('y5')
print(y5)
print('y6')
print(y6)

y4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
y5
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
y6
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
# np.random.rand() parameter 로 개수,행,열
# rand() 0~1 사이의 난수
# np.random.randn() parameter 로 개수 , 행,열
# randn() 평균이 0, 표준편차 1을 따르는 난수 발생
data_rand = np.random.rand(10)
print(data_rand)
data_randn = np.random.randn(10)
print(data_randn)

[0.57083616 0.45744662 0.57906463 0.39171986 0.80282956 0.80448199
 0.6650327  0.53355659 0.61052204 0.79010309]
[ 0.34570705  1.76853719  0.46970488 -0.16450801 -0.85049686  0.83676877
 -0.18565378 -0.08060681  1.27183169  1.09853008]


In [8]:
list1=[[1,11],[2,12],[3,13]]
np_arr=np.array(list1)
print(np_arr)
# 슬라이싱 직관적
print(np_arr[1][1])
print(np_arr[1,1])
# [시작값:끝값 , 인덱스] 시작값부터 끝값까지의 인덱스에 있는 값을 nparray 형태로 꺼냄
print(np_arr[:,1])
print(np_arr[:2,0])

[[ 1 11]
 [ 2 12]
 [ 3 13]]
12
12
[11 12 13]
[1 2]


In [9]:
a=np.arange(1,13).reshape(3,4)
print(a)
# 보통 이런 다차원 배열의 연산은 반복문이 필요한데
# numpy 는 broadcast 를 지원 iterator을 알아서 수행해준다고 보면됨
# squareroot sqrt(nparray) 제곱근
np.sqrt(a)
# mean(nparray) 평균값
np.mean(a) #a.mean()
# sum(nparray) 배열을 전부 합한 값
np.sum(a), # a.sum()
np.sum(a, axis=0) # 열합계
np.sum(a, axis=1) # 행합계
np.sqrt(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [10]:
b=[[5,3,4],[2,5,1],[7,6,9]]
arr_b=np.array(b)
# sort(nparray) 기본 정렬 default 값 행기준 오름차순 정렬
# np.sort(arr_b)
# np.sort(arr_b, axis=1) #행기준 정렬
# np.sort(arr_b, axis=0) #열기준 정렬
# np.sort(arr_b, axis=0)[::-1] #내림차순 열기준 정렬
# ##내림차순 정렬은 열기준만 가능
# 전치행렬이란? 행,열을 바꿈 예시 1행0열이 0행1열
# arr_b.transpose() #전치행렬

array([[5, 2, 7],
       [3, 5, 6],
       [4, 1, 9]])

In [14]:
# np.unique(nparray) 중복제거,오름차순 정렬
ages = np.array([20,21,23,20,22,21])
np.unique(ages)

array([20, 21, 22, 23])

In [19]:
# nparray 는 braodcasting 으로 비교 연산자 사용 가능
# np.all(nparray 비교) 각각에 and 라고 보면됨 즉 전부 True 여야 True
# np.any(nparray 비교) 각각에 or 즉 하나라도 True 면 True
# b>5 일반 리스트에선 불가
arr_b>5 #numpy배열일 때 결과
# np.all(arr_b > 5) #arr_b의 모든 요소가 5보다 클때 True
# np.any(arr_b>5) #arr_b의 어떤 요소가 5보다 클때 True

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [29]:
# np.linspace(시작값,종료값,생성갯수) default 생성갯수는 50
# 뒤에 속성 지정 가능 retstetp 샘플간 간격 반환 여부 default False, endpoint:종료값 포함여부 default True
# np.linspace(0,100,40,retstep=True)
# np.logspace(시작값,종료값,생성갯수,로그베이스) base 의 default 10
np.logspace(1,4,100)

array([   10.        ,    10.72267222,    11.49756995,    12.32846739,
          13.21941148,    14.17474163,    15.19911083,    16.29750835,
          17.475284  ,    18.73817423,    20.09233003,    21.5443469 ,
          23.101297  ,    24.77076356,    26.56087783,    28.48035868,
          30.53855509,    32.74549163,    35.11191734,    37.64935807,
          40.37017259,    43.28761281,    46.41588834,    49.77023564,
          53.36699231,    57.22367659,    61.35907273,    65.79332247,
          70.54802311,    75.64633276,    81.11308308,    86.97490026,
          93.26033469,   100.        ,   107.2267222 ,   114.97569954,
         123.28467394,   132.19411485,   141.74741629,   151.9911083 ,
         162.97508346,   174.75284   ,   187.38174229,   200.92330026,
         215.443469  ,   231.01297001,   247.7076356 ,   265.60877829,
         284.80358684,   305.38555088,   327.45491629,   351.11917342,
         376.49358068,   403.70172586,   432.87612811,   464.15888336,
      